import type { Metadata } from "next";
import { Urbanist } from "next/font/google";

import Nav from "@/components/nav";
import Sidebar from "@/components/sidebar";
import { items } from "@/components/sidebar/items";
import "react-datepicker/dist/react-datepicker.css";
import "../assets/scss/reset.scss";
import "./globals.scss";

const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lorem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <Sidebar items={items} />
        <Nav />
        {children}
      </body>
    </html>
  );
}
